<?php

class IndexController extends AdminBase{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function loginAction(){
        echo 1111;
        return false;
    }


    public function indexAction() {
        echo "hello words";
        return false;
    }

}