<?php

class SystemController extends AdminBase{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
      * Author: silie
      * Date: 2020-12-16 15:04:02
      * Description:  主题
      */
    public function settingAction(){
        $this->displays();
    }

    /**
      * Author: silie
      * Date: 2020-12-16 15:27:28
      * Description: 皮肤动画
      */
    public function alert_skinAction(){
        $this->displays();
    }

    /**
      * Author: silie
      * Date: 2020-12-16 18:30:26
      * Description: 清空缓存
      */
    public function clear_cacheAction()
    {
        $this->_redis->del('admin_menus_' . get_current_admin_id());
        api_success('清除成功');
    }

}