<?php

class SystemController extends AdminBase{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
      * Author: wyf
      * Date: 2020-12-16 15:04:02
      * Description:  主题
      */
    public function settingAction(){
        $this->displays();
    }

    /**
      * Author: wyf
      * Date: 2020-12-16 15:27:28
      * Description: 皮肤动画
      */
    public function alert_skinAction(){
        $this->displays();
    }

}