<?php

use think\Db;
use Wyf\Model\Admin\User;

class UserController extends AdminBase{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
      * Author: wyf
      * Date: 2020-12-16 16:31:26
      * Description: 检测密码
      */
    public function check_passAction(){
        $password = input('password');
        $user_pass = Db::name('user')->where('id',get_current_admin_id())->value('user_pass');
        if(md5_password($password)==$user_pass){
            api_success('密码正确');
        }else{
            api_error('密码错误');
        }
    }

    public function user_infoAction(){
        if(IS_POST){
            $data = input('post.');
            $where = array('id'=> get_current_admin_id());
            $model = new User();
            $result = $model->allowField(true)->save($data,$where);
            if($result){
                api_success('修改成功');
            }else{
                api_error('修改失败');
            }
        }
        $this->displays();
    }
}