<?php

use think\Db;

class UserController extends AdminBase{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
      * Author: wyf
      * Date: 2020-12-16 16:31:26
      * Description: 检测密码
      */
    public function check_passAction(){
        $password = input('password');
        $user_pass = Db::name('user')->where('id',get_current_admin_id())->value('user_pass');
        if(md5_password($password)==$user_pass){
            api_success('密码正确');
        }else{
            api_error('密码错误');
        }
    }
}